package com.sswork.ngbook;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table RECORD.
 */
public class Record {

    private Long id;
    /** Not-null value. */
    private String bookName;
    private long oldTime;
    /** Not-null value. */
    private String path;
    /** Not-null value. */
    private String record;

    public Record() {
    }

    public Record(Long id) {
        this.id = id;
    }

    public Record(Long id, String bookName, long oldTime, String path, String record) {
        this.id = id;
        this.bookName = bookName;
        this.oldTime = oldTime;
        this.path = path;
        this.record = record;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getBookName() {
        return bookName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBookName(String bookName) {
        this.bookName = bookName;
    }

    public long getOldTime() {
        return oldTime;
    }

    public void setOldTime(long oldTime) {
        this.oldTime = oldTime;
    }

    /** Not-null value. */
    public String getPath() {
        return path;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPath(String path) {
        this.path = path;
    }

    /** Not-null value. */
    public String getRecord() {
        return record;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRecord(String record) {
        this.record = record;
    }

}
